name: Auto Merge Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (pr) {
              try {
                await github.rest.pulls.enableAutoMerge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  merge_method: "squash"
                });
                core.info('Auto-merge enabled for PR #' + pr.number);
              } catch (error) {
                core.warning('Could not enable auto-merge for PR #' + pr.number + ': ' + error.message);
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
