name: Identify PR Conflicts

on:
  workflow_dispatch:

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up GitHub CLI
        uses: crazy-max/ghaction-setup-gh@v1
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Identify conflicts in PRs
        run: |
          echo "## Pull Request Conflict Status" > conflict_report.md
          echo "" >> conflict_report.md
          echo "| PR # | Title | Has Conflicts | Files with Conflicts |" >> conflict_report.md
          echo "|------|-------|---------------|---------------------|" >> conflict_report.md
          
          # Get all open PRs
          gh pr list --state open --json number,title,mergeable,headRefName --limit 100 | \
          jq -c '.[]' | while read pr_info; do
            PR_NUMBER=$(echo $pr_info | jq -r '.number')
            PR_TITLE=$(echo $pr_info | jq -r '.title')
            MERGEABLE=$(echo $pr_info | jq -r '.mergeable')
            HEAD_BRANCH=$(echo $pr_info | jq -r '.headRefName')
            
            if [[ "$MERGEABLE" == "CONFLICTING" ]]; then
              echo "PR #$PR_NUMBER has conflicts, checking details..."
              
              # Attempt to get conflict details
              CONFLICT_FILES=""
              git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER || true
              git checkout pr-$PR_NUMBER || true
              git merge origin/main || true
              
              # Find conflicted files
              CONFLICT_FILES=$(git diff --name-only --diff-filter=U | tr '\n' ', ' | sed 's/,$//')
              
              if [[ -z "$CONFLICT_FILES" ]]; then
                CONFLICT_FILES="Unknown (could not determine)"
              fi
              
              # Reset after checking conflicts
              git merge --abort || true
              git checkout main || true
              git branch -D pr-$PR_NUMBER || true
              
              echo "| $PR_NUMBER | $PR_TITLE | ❌ Yes | $CONFLICT_FILES |" >> conflict_report.md
            else
              echo "| $PR_NUMBER | $PR_TITLE | ✅ No | - |" >> conflict_report.md
            fi
          done
          
          cat conflict_report.md
          
      - name: Upload conflict report
        uses: actions/upload-artifact@v3
        with:
          name: pr-conflict-report
          path: conflict_report.md
